import type { Metadata } from "next";
import { geistMono, geistSans } from "@/fonts";
import { Providers } from "@/lib/providers";
import "./globals.css";
import { Sidebar } from "@/components/layouts/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <Providers>
          <div className="h-svh flex">
            <Sidebar />
            <main className="flex-1 min-h-0 bg-gray-600">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
